### ISSUE TITLE
Custom tags?

### ISSUE THREAD

**Issue by Ihsan48** [IvanCraft623/RankSystem#22]
<h1> Does this plugin Provide Custom api tags? because I really need </h1>

I want to make Tag Integration against Clans, Factions, and more

**Comment by IvanCraft623** [comment]
> Does this plugin Provide Custom api tags? because I really need

Nop

**Comment by IvanCraft623** [comment]
I will probably implement it

**Comment by IvanCraft623** [comment]
@Ihsan48 https://github.com/IvanCraft623/RankSystem/wiki/Tags#register-a-custom-tag
