### ISSUE TITLE
Prefix issues 

### ISSUE THREAD

**Issue by h20plex** [IvanCraft623/RankSystem#23]
So i was wondering are prefix for different ranks suppose to merge so if you have two different ranks it gives you both prefixs cause thats a problem i feel that the rank with higher authority in the list is the only prefix that should show in chat an above players head idk if you under what i am saying hopefully you do

**Comment by h20plex** [comment]
Heres an example 
![626B9127-0212-4F63-BE4C-A84782E4FB10](https://user-images.githubusercontent.com/28747431/182052371-c9976bfc-6ee5-4641-8e61-9492a29e9e17.png)

**Comment by IvanCraft623** [comment]
Your wishes are now possible with the new tagging system:

In the `config.yml` file locate `nametag` =>`format`:
Replace the `{nametag_ranks_prefix}` tag with `{nametag_highest-rank_prefix}`.

**Comment by h20plex** [comment]
Thank thats lit your amazing
