### ISSUE TITLE
Factions Support

### ISSUE THREAD

**Issue by ErwanScraft** [IvanCraft623/RankSystem#25]
This plugin is good, but please add support for factions plugins like PiggyFactions and FactionsMaster

**Comment by IvanCraft623** [comment]
Another plugin must be in charge of supporting them, either the Factions plugins or a separate one. You can contact the developers of these plugins and suggest them to support RankSystem using the API: https://github.com/IvanCraft623/RankSystem/wiki/Tags#register-a-custom-tag
