### ISSUE TITLE
[Suggest] Two Suggestions

### ISSUE THREAD

**Issue by BroCrows** [IvanCraft623/RankSystem#3]
Hello! Welcome to two different suggestions!
First off, add an option to disable multiple ranks, some people dont use it!

Second off, make the Hierarchy act as PurePerm's inheritance feature as filling up ranks with unneeded perms is insanely annoying while the rank behind the other rank already has the perms.

**Comment by IvanCraft623** [comment]
Hi ZZWILLIAMXXTrue!

Regarding the first suggestion, it would not make much sense since it is one of the main features of the plugin, and the plugin already complies with the second suggestion, the permissions of the ranges are inherited to the players.

Thanks for your suggestions.
