### ISSUE TITLE
API

### ISSUE THREAD

**Issue by UnknownNull** [IvanCraft623/RankSystem#33]
Implement an api system

**Comment by IvanCraft623** [comment]
There is already an API, you can take a look to the [wiki](https://github.com/IvanCraft623/RankSystem/wiki) or the source code.

**Comment by UnknownNull** [comment]
> There is already an API, you can take a look to the [wiki](https://github.com/IvanCraft623/RankSystem/wiki) or the source code.

getRankTime ?
like getRaank
