### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by ImDev68** [IvanCraft623/RankSystem#36]
Actualiza el plugin a la versión más actual pues da este error 
IvanCraft623\RankSystem\libs\poggit\libasynql\generic\GenericStatementImpl::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home/container/plugins/Ranks/src/IvanCraft623/RankSystem/libs/poggit/libasynql/generic/GenericStatementImpl.php:233

public function jsonSerialize(){
		return [
			"name" => $this->name,
			"query" => $this->query,
			"doc" => $this->doc,
			"variables" => $this->variables,
			"file" => $this->file,
			"lineNo" => $this->lineNo,
		];

**Comment by sulimanzeen** [comment]
i think it's because of PHP 8.1 update. for this plugin. since now Pocketmine requires PHP 8.1

Error only happens if your using mysql

**Comment by IvanCraft623** [comment]
Fixed by f0908ec5b2079b84852571adf2ac651107de0045
