### ISSUE TITLE
Permissions bug

### ISSUE THREAD

**Issue by UnknownNull** [IvanCraft623/RankSystem#48]
The default perms are not loaded in the lower versions like 1.19.10 / 1.20 and if the account is opened, the person will leave the server and cannot return...

More: https://github.com/NetherGamesMC/PocketMine-MP/issues/360#event-9764362599

**Comment by IvanCraft623** [comment]
I'm confused as to what the actual issue is here, the plugin does not touch anything related to protocol or versions

**Comment by UnknownNull** [comment]
Let them see that your plugin has several major problems
For example, when the player enters the server, it lags for several seconds, and nothing except the map is loaded well for it, and... (from WDPE) is used.

**Comment by UnknownNull** [comment]
Another one is that there is a problem with some permissions, and the other is that it does not have the ability to reload data, and this causes the server to be turned off and on every time to save the data.

**Comment by IvanCraft623** [comment]
> For example, when the player enters the server, it lags for several seconds, and nothing except the map is loaded well for it, and... (from WDPE) is used.

Without WaterdogPE works well?

**Comment by UnknownNull** [comment]
> 

Forget this matter, other matters need to be followed up
