### ISSUE TITLE
Suffix

### ISSUE THREAD

**Issue by dvodany** [IvanCraft623/RankSystem#8]
Hi, I just have an idea it will be soo cool to have a suffix option too. 
    I mean if we can manage ranks directly from the game(or inside the ranks.yml), we have an option to edit prefix and I think it will be great if we'll be able to change player's suffix too. 
   Thanks and I appreciate all work that you've put into this plugin, I LOVE IT!

**Comment by IvanCraft623** [comment]
Now you can add suffix with the new tag system, Go to config.yml
